(()=>{'use strict';
const CACHE='machitan.kuyakusho.map.v1',DAY='machitan.kuyakusho.day.v1.',M=111320,DISC_ACC=20,DIST_ACC=35,DISC_RADIUS=25,ACC_BONUS=5,EFFECT_RADIUS=30,GRID=2;
const ST=[['土づくり',0],['芽吹きの畑',1000],['花畑',3000],['緑の広場',6000],['小さな林',10000],['まちの森',20000]],$=id=>document.getElementById(id);
const read=k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const dk=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,key=d=>DAY+(d||dk());
let map=read(CACHE),day=null,found=new Set(),watch=null,prevDist=null,prevDisc=null,pos=null,timer=null,toastTimer=null;
function blank(){return{v:3,date:dk(),found:[],dist:0,elapsed:0,status:'idle',startedAt:null,gps:{samples:0,accepted:0,rejected:0,accSum:0,best:null,worst:null,jumps:0,distanceSamples:0},updated:Date.now()}}
function fa(a){return a>=1000?`${(a/10000).toFixed(2)} ha`:`${Math.round(a).toLocaleString()} m²`}function fd(m){return m>=1000?`${(m/1000).toFixed(2)} km`:`${Math.round(m)} m`}function ft(ms){const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function loadDay(){day=read(key())||blank();day.gps=Object.assign(blank().gps,day.gps||{});if(day.status==='running'){if(day.startedAt)day.elapsed=(day.elapsed||0)+Math.max(0,Date.now()-day.startedAt);day.status='paused';day.startedAt=null}found=new Set((day.found||[]).filter(i=>Number.isInteger(i)&&i>=0&&i<map.points.length));store()}
function store(){if(!day)return;day.found=[...found];day.updated=Date.now();save(key(day.date),day)}function live(){return(day.elapsed||0)+(day.status==='running'&&day.startedAt?Date.now()-day.startedAt:0)}function commit(){if(day?.status==='running'&&day.startedAt){day.elapsed+=Math.max(0,Date.now()-day.startedAt);day.startedAt=null}}
function p(i){const q=map.points[i];return{lat:q[2],lng:q[3]}}function meters(a,b){const r=6371000,k=Math.PI/180,x1=a.lat*k,x2=b.lat*k,da=(b.lat-a.lat)*k,dl=(b.lng-a.lng)*k,h=Math.sin(da/2)**2+Math.cos(x1)*Math.cos(x2)*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(h)))}function seg(q,a,b){const rl=((a.lat+b.lat+q.lat)/3)*Math.PI/180,mx=M*Math.cos(rl),bx=(b.lng-a.lng)*mx,by=(b.lat-a.lat)*M,px=(q.lng-a.lng)*mx,py=(q.lat-a.lat)*M,l=bx*bx+by*by;if(!l)return Math.hypot(px,py);const t=Math.max(0,Math.min(1,(px*bx+py*by)/l));return Math.hypot(px-bx*t,py-by*t)}
function gps(t,w=false){$('gps').textContent=t;$('gps').classList.toggle('warn',w)}
function onGeo(g){if(day.status!=='running')return;const n={lat:g.coords.latitude,lng:g.coords.longitude,acc:Number.isFinite(g.coords.accuracy)?g.coords.accuracy:9999,ts:g.timestamp||Date.now()};pos=n;day.gps.samples++;
 if(n.acc<=DIST_ACC){day.gps.distanceSamples++;if(prevDist){const d=meters(prevDist,n),sec=Math.max((n.ts-prevDist.ts)/1000,.5),noise=Math.max(3,Math.min(10,(prevDist.acc+n.acc)*.16)),limit=Math.max(100,sec*6+prevDist.acc+n.acc);if(d>=noise&&d<=limit)day.dist+=d;else if(d>limit)day.gps.jumps++}prevDist=n}
 if(n.acc>DISC_ACC){day.gps.rejected++;store();gps(`GPS精度を調整中（約${Math.round(n.acc)}m）`,true);render();return}
 day.gps.accepted++;day.gps.accSum+=n.acc;day.gps.best=day.gps.best===null?n.acc:Math.min(day.gps.best,n.acc);day.gps.worst=day.gps.worst===null?n.acc:Math.max(day.gps.worst,n.acc);
 const rad=DISC_RADIUS+Math.min(ACC_BONUS,n.acc),discValid=prevDisc?meters(prevDisc,n)<=Math.max(120,Math.max((n.ts-prevDisc.ts)/1000,.5)*6+prevDisc.acc+n.acc):false;let add=0;
 for(let i=0;i<map.points.length;i++){if(found.has(i))continue;const q=p(i);if(meters(q,n)<=rad||(prevDisc&&discValid&&seg(q,prevDisc,n)<=rad)){found.add(i);add++}}
 prevDisc=n;store();render();gps(`街を育てています（GPS 約${Math.round(n.acc)}m）`);if(add)toast(`${add}か所、街が育ちました`)}
function onGeoErr(e){gps(e.code===1?'位置情報が許可されていません':e.code===2?'現在地を取得できません':'GPS取得がタイムアウトしました',true)}function startGeo(){if(!navigator.geolocation){gps('位置情報に対応していません',true);return false}if(watch!==null)navigator.geolocation.clearWatch(watch);watch=navigator.geolocation.watchPosition(onGeo,onGeoErr,{enableHighAccuracy:true,maximumAge:1000,timeout:15000});return true}function stopGeo(){if(watch!==null){navigator.geolocation.clearWatch(watch);watch=null}prevDist=null;prevDisc=null}
function start(){if(!startGeo())return;day.status='running';day.startedAt=Date.now();timer&&clearInterval(timer);timer=setInterval(()=>{$('time').textContent=ft(live())},500);store();render();gps('GPSを取得中')}function finish(){commit();day.status='finished';stopGeo();timer&&clearInterval(timer);timer=null;store();render();gps('今日の街育てを終了');toast('今日の結果を保存しました')}
function area(ids){if(!ids.length)return 0;const first=p(ids[0]),ml=M*Math.cos(first.lat*Math.PI/180),cells=new Set(),r=Math.ceil(EFFECT_RADIUS/GRID);for(const i of ids){const q=p(i),rx=(q.lng-first.lng)*ml,ry=(q.lat-first.lat)*M,cx=Math.round(rx/GRID),cy=Math.round(ry/GRID);for(let dx=-r;dx<=r;dx++)for(let dy=-r;dy<=r;dy++){const x=(cx+dx)*GRID,y=(cy+dy)*GRID;if(Math.hypot(x-rx,y-ry)<=EFFECT_RADIUS)cells.add(`${cx+dx}:${cy+dy}`)}}return cells.size*GRID*GRID}
function stage(a){let x=ST[0],next=null;for(let i=0;i<ST.length;i++)if(a>=ST[i][1]){x=ST[i];next=ST[i+1]||null}return{x,next}}function proj(lat,lng,w,h,pad=25){const [a,b,c,d]=map.bounds,ls=Math.max(.0001,b-a),os=Math.max(.0001,d-c);return[pad+(lng-c)/os*(w-pad*2),h-pad-(lat-a)/ls*(h-pad*2)]}
function draw(){const c=$('map'),x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#eef3e9';x.fillRect(0,0,w,h);for(let i=0;i<map.points.length;i++){const q=map.points[i],[a,b]=proj(q[2],q[3],w,h);x.beginPath();x.arc(a,b,found.has(i)?3:1.6,0,Math.PI*2);x.fillStyle=found.has(i)?'#58a45d':'#aab3aa';x.fill()}if(pos){const [a,b]=proj(pos.lat,pos.lng,w,h);x.fillStyle='#246399';x.beginPath();x.arc(a,b,6,0,Math.PI*2);x.fill()}}
function controls(){const s=day.status;$('start').classList.toggle('hidden',s==='running');$('start').textContent=s==='paused'?'街育てを再開':'街育てを開始';$('finish').classList.toggle('hidden',s!=='running');if($('pause'))$('pause').classList.add('hidden');if($('resume'))$('resume').classList.add('hidden')}
function render(){const ids=[...found],a=area(ids),st=stage(a),n=ids.length;$('stage').textContent=st.x[0];$('stageDesc').textContent=st.x[0]==='土づくり'?'まだ小さな一歩。ここから緑が芽を出します。':'歩いた場所から街が育っています。';$('area').textContent=fa(a);$('growthFill').style.width=st.next?`${Math.min(100,Math.round((a-st.x[1])/(st.next[1]-st.x[1])*100))}%`:'100%';$('next').textContent=st.next?`次は「${st.next[0]}」まで あと${fa(Math.max(0,st.next[1]-a))}`:'最高ステージまで育ちました';$('found').textContent=`${n.toLocaleString()} / ${map.points.length.toLocaleString()}`;$('pct').textContent=(n/map.points.length*100).toFixed(1)+'%';$('dist').textContent=fd(day.dist||0);$('time').textContent=ft(live());$('avgAcc').textContent=day.gps.accepted?`${(day.gps.accSum/day.gps.accepted).toFixed(1)}m`:'-';$('rejected').textContent=`${day.gps.rejected}件 / 飛び${day.gps.jumps}件`;if($('snapshotCard'))$('snapshotCard').classList.add('hidden');draw();controls();history()}
function history(){let o='';for(let i=0;i<14;i++){const d=new Date();d.setDate(d.getDate()-i);const k=dk(d),s=read(key(k));if(!s)continue;const ids=(s.found||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<map.points.length);o+=`<div><b>${k.slice(5).replace('-','/')} ${ids.length}か所 / ${fa(area(ids))}</b><br><span class="muted">${fd(s.dist||0)} / ${ft(s.elapsed||0)}</span></div>`}$('history').innerHTML=o||'<div class="muted">まだ記録がありません。</div>'}
function reset(){if(!confirm('今日の記録を0に戻しますか？'))return;commit();stopGeo();timer&&clearInterval(timer);timer=null;day=blank();found=new Set();pos=null;store();render();gps('街育て前')}
async function exportData(){const dates=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith(DAY))dates.push(k.slice(DAY.length))}dates.sort();const days=dates.map(date=>{const s=read(key(date))||{},ids=(s.found||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<map.points.length);return{date,foundCount:ids.length,grownAreaSquareMeters:area(ids),referenceDistanceMeters:Math.round(s.dist||0),elapsedMilliseconds:Math.round(s.elapsed||0),gps:s.gps}}),data={format:'machitan-kuyakusho-single',version:3,exportedAt:new Date().toISOString(),privacy:{rawGpsTrackIncluded:false,coordinatesIncluded:false},days},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),name=`machitan-kuyakusho-${dk().replaceAll('-','')}.json`,file=new File([blob],name,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'まちたん！区役所テスト'});return}catch{}}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('on'),1800)}
if(!map?.points?.length){gps('固定地図を読み込めませんでした',true);return}loadDay();$('app').classList.remove('hidden');$('locked').classList.add('hidden');$('start').onclick=start;$('finish').onclick=finish;$('reset').onclick=reset;$('exportData').onclick=exportData;window.addEventListener('beforeunload',()=>{commit();store()});document.addEventListener('visibilitychange',()=>{store();if(!document.hidden&&day.status==='running'&&watch===null)startGeo()});render();if(day.status==='paused')gps('前回の計測が中断されました。再開を押してください',true);
})();