(()=>{'use strict';
const DAY_PREFIX='machitan.shinozaki.towngrowth.day.v2.',METRIC_PREFIX='machitan.shinozaki.qa.day.v1.',MAP_CACHE='machitan.shinozaki.fixedmap.v2',M_PER_LAT=111320,EFFECT_RADIUS=30,GRID=2;
const $=id=>document.getElementById(id);
const read=k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}};
const fmtDate=()=>{const d=new Date();return`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`};
function uniqueArea(map,indices){if(!indices.length)return 0;const first=map.points[indices[0]],lat0=first[2],lng0=first[3],mlng=M_PER_LAT*Math.cos(lat0*Math.PI/180),cells=new Set(),r=Math.ceil(EFFECT_RADIUS/GRID);for(const i of indices){const p=map.points[i];if(!p)continue;const rx=(p[3]-lng0)*mlng,ry=(p[2]-lat0)*M_PER_LAT,cx=Math.round(rx/GRID),cy=Math.round(ry/GRID);for(let dx=-r;dx<=r;dx++)for(let dy=-r;dy<=r;dy++){const x=(cx+dx)*GRID,y=(cy+dy)*GRID;if(Math.hypot(x-rx,y-ry)<=EFFECT_RADIUS)cells.add(`${cx+dx}:${cy+dy}`)}}return cells.size*GRID*GRID}
function stageName(area){if(area>=20000)return'まちの森';if(area>=10000)return'小さな林';if(area>=6000)return'緑の広場';if(area>=3000)return'花畑';if(area>=1000)return'芽吹きの畑';return'土づくり'}
function collect(){const map=read(MAP_CACHE);if(!map?.points?.length)throw Error('固定地図が端末にありません。');const dates=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith(DAY_PREFIX))dates.push(k.slice(DAY_PREFIX.length))}dates.sort();const days=dates.map(date=>{const s=read(DAY_PREFIX+date)||{},q=read(METRIC_PREFIX+date)||{},indices=[...new Set((s.found||[]).filter(i=>Number.isInteger(i)&&i>=0&&i<map.points.length))].sort((a,b)=>a-b),area=uniqueArea(map,indices),accepted=q.acceptedAccuracySamples||0;return{date,status:s.status||'unknown',foundCount:indices.length,totalPoiCount:map.points.length,completionPercentage:Math.round(indices.length/map.points.length*100),grownAreaSquareMeters:area,townStage:stageName(area),referenceDistanceMeters:Math.round(s.dist||0),elapsedMilliseconds:Math.round(s.elapsed||0),foundIndices:indices,gps:{samples:q.samples||0,acceptedAccuracySamples:accepted,rejectedAccuracySamples:q.rejectedAccuracySamples||0,averageAcceptedAccuracyMeters:accepted?Math.round((q.accuracySum/accepted)*10)/10:null,bestAccuracyMeters:q.bestAccuracy===null||q.bestAccuracy===undefined?null:Math.round(q.bestAccuracy*10)/10,worstAcceptedAccuracyMeters:q.worstAccuracy===null||q.worstAccuracy===undefined?null:Math.round(q.worstAccuracy*10)/10,invalidJumpSamples:q.invalidJumpSamples||0},updatedAt:s.updated?new Date(s.updated).toISOString():null}});return{format:'machitan-shinozaki-qa',version:1,exportedAt:new Date().toISOString(),event:{name:'篠崎 街育てテスト',mapId:map.id||'shinozaki-fixed',totalPoiCount:map.points.length,effectRadiusMeters:EFFECT_RADIUS,areaGridSizeMeters:GRID},privacy:{rawGpsTrackIncluded:false,coordinatesIncluded:false,poiNamesIncluded:false},summary:{testDays:days.length,firstDate:days[0]?.date||null,lastDate:days.at(-1)?.date||null},days}}
async function exportData(){try{const data=collect(),text=JSON.stringify(data,null,2),fileName=`machitan-shinozaki-test-${fmtDate()}.json`,blob=new Blob([text],{type:'application/json'}),file=new File([blob],fileName,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'まちたん！ 篠崎テストデータ',text:`篠崎の街育てテスト ${data.summary.testDays}日分`});return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){alert(e?.message||'テストデータを書き出せませんでした。')}}
const button=$('exportData');if(button)button.addEventListener('click',exportData);
})();