(()=>{'use strict';
const PAYLOAD=(window.SHINOZAKI_DATA||[]).join(''),MAP_ID='shinozaki-fixed-20260810-v1',MAP_CACHE='machitan.shinozaki.fixedmap.v2',KEY_CACHE='machitan.shinozaki.key.v1',DAY_PREFIX='machitan.shinozaki.towngrowth.day.v2.',MAX_ACC=20,MIN_MOVE=4,MAX_JUMP=30,MAX_SPEED=4.5,DISCOVERY_RADIUS=25,ACC_BONUS=5,EFFECT_RADIUS=30,GRID=2,M_PER_LAT=111320;
const STAGES=[['soil','土づくり','まだ小さな一歩。ここから緑が芽を出します。',0],['sprout','芽吹きの畑','歩いた場所に、やわらかな芽が広がっています。',1000],['flower','花畑','緑がつながり、街に花の景色が生まれました。',3000],['square','緑の広場','みんなが集まれるほど、緑が大きく育っています。',6000],['grove','小さな林','点だった緑が重なり、街の林になりました。',10000],['forest','まちの森','歩いた軌跡が、街を包む大きな森になりました。',20000]];
const $=id=>document.getElementById(id);let map=null,day=null,found=new Set(),watch=null,prev=null,pos=null,started=0,timer=null,toastTimer=null,areaCache={sig:'',value:0};
const b64u=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))};const json=k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,dayKey=k=>DAY_PREFIX+(k||dateKey());
function blank(){return{v:2,date:dateKey(),found:[],dist:0,elapsed:0,status:'idle',updated:Date.now()}}function fmtArea(a){return a>=1000?`${(a/10000).toFixed(2)} ha`:`${Math.round(a).toLocaleString()} m²`}function fmtDist(m){return m>=1000?`${(m/1000).toFixed(2)} km`:`${Math.round(m)} m`}function fmtTime(ms){const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
async function decrypt(keyText){const keyBytes=b64u(keyText.trim()),all=b64u(PAYLOAD),iv=all.slice(0,12),cipher=all.slice(12),key=await crypto.subtle.importKey('raw',keyBytes,{name:'AES-GCM'},false,['decrypt']),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher),gz=new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip')),text=await new Response(gz).text(),obj=JSON.parse(text);if(obj.v!==3||!Array.isArray(obj.points)||obj.points.length!==1002)throw Error('固定地図を確認できませんでした。');return{id:MAP_ID,name:obj.name,points:obj.points,bounds:obj.bounds}}
async function unlock(keyText){try{$('lockMsg').textContent='固定地図を準備中…';const obj=await decrypt(keyText);save(MAP_CACHE,obj);localStorage.setItem(KEY_CACHE,keyText.trim());map=obj;history.replaceState(null,'',location.pathname+location.search);show();toast('篠崎の固定地図を読み込みました')}catch(e){$('lockMsg').textContent='キーが違うか、固定地図を読み込めませんでした。'}}
function loadDay(){day=json(dayKey())||blank();if(day.status==='running')day.status='paused';found=new Set((day.found||[]).filter(i=>Number.isInteger(i)&&i>=0&&i<map.points.length));store()}function store(){if(!day)return;day.found=[...found];day.updated=Date.now();save(dayKey(day.date),day)}function live(){return(day?.elapsed||0)+(day?.status==='running'&&started?Date.now()-started:0)}function commitTime(){if(day?.status==='running'&&started){day.elapsed+=Date.now()-started;started=0}}
function asPoint(p){return{lat:p[2],lng:p[3]}}function meters(a,b){const r=6371000,k=Math.PI/180,x1=a.lat*k,x2=b.lat*k,da=(b.lat-a.lat)*k,dl=(b.lng-a.lng)*k,h=Math.sin(da/2)**2+Math.cos(x1)*Math.cos(x2)*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(h)))}function seg(p,a,b){const rl=((a.lat+b.lat+p.lat)/3)*Math.PI/180,mx=M_PER_LAT*Math.cos(rl),my=M_PER_LAT,bx=(b.lng-a.lng)*mx,by=(b.lat-a.lat)*my,px=(p.lng-a.lng)*mx,py=(p.lat-a.lat)*my,l=bx*bx+by*by;if(!l)return Math.hypot(px,py);const t=Math.max(0,Math.min(1,(px*bx+py*by)/l));return Math.hypot(px-bx*t,py-by*t)}
function gpsText(t,w=false){$('gps').textContent=t;$('gps').classList.toggle('warn',w)}function onGeo(g){if(day.status!=='running')return;const n={lat:g.coords.latitude,lng:g.coords.longitude,acc:g.coords.accuracy??9999,ts:g.timestamp||Date.now(),speed:g.coords.speed};pos=n;if(n.acc>MAX_ACC){gpsText(`GPS精度を調整中（約${Math.round(n.acc)}m）`,true);renderNearest();draw();return}gpsText(`街を育てています（GPS 約${Math.round(n.acc)}m）`);let valid=false;if(prev){const m=meters(prev,n),sec=Math.max((n.ts-prev.ts)/1000,.5),calc=m/sec,reported=Number.isFinite(n.speed)&&n.speed>=0?n.speed:null,bad=m>Math.max(MAX_JUMP,sec*MAX_SPEED+5)||calc>MAX_SPEED||(reported!==null&&reported>MAX_SPEED);if(!bad){valid=true;if(m>=MIN_MOVE)day.dist+=m}}const rad=DISCOVERY_RADIUS+Math.min(ACC_BONUS,n.acc||0);let add=0;for(let i=0;i<map.points.length;i++){if(found.has(i))continue;const p=asPoint(map.points[i]);if(meters(p,n)<=rad||(prev&&valid&&seg(p,prev,n)<=rad)){found.add(i);add++}}prev=n;if(add)areaCache.sig='';store();render();if(add)toast(`${add}か所、街が育ちました`)}function onGeoErr(e){gpsText(e.code===1?'位置情報が許可されていません':e.code===2?'現在地を取得できません':'GPS取得がタイムアウトしました',true)}function startGeo(){if(!navigator.geolocation){gpsText('このブラウザは位置情報に対応していません',true);return false}stopGeo();watch=navigator.geolocation.watchPosition(onGeo,onGeoErr,{enableHighAccuracy:true,maximumAge:1000,timeout:15000});return true}function stopGeo(){if(watch!==null){navigator.geolocation.clearWatch(watch);watch=null}prev=null}
function start(){if(!startGeo())return;if(day.status==='finished')day.status='idle';day.status='running';started=Date.now();timer=setInterval(()=>{$('time').textContent=fmtTime(live())},500);gpsText('GPSを取得中');store();controls()}function pause(){if(day.status!=='running')return;commitTime();day.status='paused';stopGeo();clearInterval(timer);timer=null;store();render();gpsText('街育てを一時停止中')}function resume(){if(day.status==='paused')start()}function finish(){commitTime();day.status='finished';stopGeo();clearInterval(timer);timer=null;store();render();gpsText('今日の街育てを終了');toast('今日の街を保存しました')}
function uniqueArea(){const sig=[...found].sort((a,b)=>a-b).join(',');if(areaCache.sig===sig)return areaCache.value;if(!found.size){areaCache={sig,value:0};return 0}const first=asPoint(map.points[found.values().next().value]),mlng=M_PER_LAT*Math.cos(first.lat*Math.PI/180),cells=new Set(),r=Math.ceil(EFFECT_RADIUS/GRID);for(const i of found){const p=asPoint(map.points[i]),cx=Math.round(((p.lng-first.lng)*mlng)/GRID),cy=Math.round(((p.lat-first.lat)*M_PER_LAT)/GRID),rx=(p.lng-first.lng)*mlng,ry=(p.lat-first.lat)*M_PER_LAT;for(let dx=-r;dx<=r;dx++)for(let dy=-r;dy<=r;dy++){const x=(cx+dx)*GRID,y=(cy+dy)*GRID;if(Math.hypot(x-rx,y-ry)<=EFFECT_RADIUS)cells.add(`${cx+dx}:${cy+dy}`)}}const value=cells.size*GRID*GRID;areaCache={sig,value};return value}
function stageFor(a){let idx=0;for(let i=0;i<STAGES.length;i++)if(a>=STAGES[i][3])idx=i;const s=STAGES[idx],n=STAGES[idx+1]||null;if(!n)return{s,n:null,p:100,remain:0};return{s,n,p:Math.max(0,Math.min(100,Math.round((a-s[3])/(n[3]-s[3])*100))),remain:Math.max(0,n[3]-a)}}function petalPoints(lat,lng,seed){let h=0;for(const c of String(seed))h=(h*31+c.charCodeAt(0))>>>0;const rot=((h%1000)/1000)*(Math.PI*2/5),mlng=Math.max(1,M_PER_LAT*Math.cos(lat*Math.PI/180)),arr=[];for(let i=0;i<40;i++){const ang=rot+i/40*Math.PI*2,w=(1+Math.cos(5*(ang-rot)))/2,r=17+(30-17)*Math.pow(w,.72),north=Math.cos(ang)*r,east=Math.sin(ang)*r;arr.push([lat+north/M_PER_LAT,lng+east/mlng])}return arr}
function project(lat,lng,w,h,pad){const [minLat,maxLat,minLng,maxLng]=map.bounds,ls=Math.max(.0001,maxLat-minLat),os=Math.max(.0001,maxLng-minLng);return[pad+(lng-minLng)/os*(w-pad*2),h-pad-(lat-minLat)/ls*(h-pad*2)]}function draw(){const c=$('map'),x=c.getContext('2d'),w=c.width,h=c.height,pad=25;x.fillStyle='#eef3e9';x.fillRect(0,0,w,h);x.fillStyle='#aab3aa';for(let i=0;i<map.points.length;i++){if(found.has(i))continue;const p=map.points[i],[a,b]=project(p[2],p[3],w,h,pad);x.beginPath();x.arc(a,b,1.8,0,Math.PI*2);x.fill()}x.fillStyle='rgba(88,164,93,.52)';x.strokeStyle='rgba(55,95,58,.7)';x.lineWidth=1.2;for(const i of found){const p=map.points[i],shape=petalPoints(p[2],p[3],i);x.beginPath();shape.forEach((q,j)=>{const [a,b]=project(q[0],q[1],w,h,pad);j?x.lineTo(a,b):x.moveTo(a,b)});x.closePath();x.fill();x.stroke()}if(pos){const [a,b]=project(pos.lat,pos.lng,w,h,pad);x.fillStyle='#246399';x.beginPath();x.arc(a,b,6,0,Math.PI*2);x.fill();x.strokeStyle='#fff';x.lineWidth=2;x.stroke()}}
function renderNearest(){if(!pos){$('nearest').textContent='街育てを開始すると、最寄りの未攻略ポイポイを表示します。';return}let q=null,b=Infinity;for(let i=0;i<map.points.length;i++){if(found.has(i))continue;const d=meters(asPoint(map.points[i]),pos);if(d<b){b=d;q=map.points[i]}}$('nearest').textContent=q?`次に育てられそう：${q[0]}　あと約${Math.round(b)}m`:'今日の固定地図をすべて育てました。'}function controls(){const s=day.status;$('start').classList.toggle('hidden',!['idle','finished'].includes(s));$('pause').classList.toggle('hidden',s!=='running');$('resume').classList.toggle('hidden',s!=='paused');$('finish').classList.toggle('hidden',!['running','paused'].includes(s))}
function render(){const a=uniqueArea(),st=stageFor(a),n=found.size,pct=Math.round(n/map.points.length*100);$('stage').textContent=st.s[1];$('stageDesc').textContent=st.s[2];$('area').textContent=fmtArea(a);$('growthFill').style.width=st.p+'%';$('next').textContent=st.n?`次は「${st.n[1]}」まで あと${fmtArea(st.remain)}`:'最高ステージまで育ちました';$('found').textContent=`${n.toLocaleString()} / ${map.points.length.toLocaleString()}`;$('pct').textContent=pct+'%';$('dist').textContent=fmtDist(day.dist||0);$('time').textContent=fmtTime(live());renderNearest();draw();controls();renderHistory()}
function renderHistory(){let out='';for(let i=0;i<14;i++){const d=new Date();d.setDate(d.getDate()-i);const k=dateKey(d),s=json(dayKey(k));if(!s)continue;const indices=new Set((s.found||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<map.points.length)),old=found;found=indices;areaCache.sig='';const a=uniqueArea();found=old;areaCache.sig='';out+=`<div><b>${k.slice(5).replace('-','/')}　${fmtArea(a)}</b><br><span class="muted">${indices.size.toLocaleString()}か所 / ${fmtDist(s.dist||0)} / ${fmtTime(s.elapsed||0)}</span></div>`}$('history').innerHTML=out||'<div class="muted">まだ記録がありません。</div>'}
function reset(){if(!confirm('今日育てた街を0に戻しますか？'))return;commitTime();stopGeo();clearInterval(timer);timer=null;started=0;day=blank();found=new Set();pos=null;areaCache={sig:'',value:0};store();render();gpsText('街育て前')}function toast(t){$('toast').textContent=t;$('toast').classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('on'),2000)}function show(){$('locked').classList.add('hidden');$('app').classList.remove('hidden');$('date').textContent=dateKey();loadDay();render()}
$('unlock').onclick=()=>unlock($('keyInput').value);$('start').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;$('finish').onclick=finish;$('reset').onclick=reset;document.addEventListener('visibilitychange',()=>{if(document.hidden)store()});window.addEventListener('beforeunload',()=>{commitTime();store()});
(async()=>{const cached=json(MAP_CACHE);if(cached?.id===MAP_ID&&cached?.points?.length===1002){map=cached;show();return}const hashKey=new URLSearchParams(location.hash.slice(1)).get('k')||localStorage.getItem(KEY_CACHE)||'';if(hashKey){await unlock(hashKey);return}$('locked').classList.remove('hidden')})();
})();
